source = ./keybindings.conf
monitor=desc:BNQ BenQ G920WL 1C902162026,preferred,0x0,auto #monitor intr
monitor=eDP-1,preferred,1440x0,1 #in-built
monitor=desc:Dell Inc. DELL S2721HGF BNJS4H3, preferred, 3360x0, auto #monitor doma
# monitor=desc:HP Inc. HP E27 G5 CNC32627XT, preferred, 1440x-1080, auto #polygon

# aby mi nemizel kurzor, kvůli nvidii
env = HYPRCURSOR_THEME,lilith
env = HYPRCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

cursor {
    no_hardware_cursors = true
    hide_on_key_press = true
}

general {
    border_size = 2

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = dwindle
}


# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = slave
}

# https://wiki.hyprland.org/Configuring/Variables/#misc
misc {
    middle_click_paste = false
}
# debug.vfr = false

input {
    kb_layout = cz
    kb_variant = qwerty
	numlock_by_default = true
    touchpad {
        natural_scroll = false
    }
}

animations {
    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    bezier = almostLinear,0.5,0.5,0.75,1.0
    bezier = quick,0.15,0,0.1,1

    animation = global, 1, 10, default
    animation = border, 1, 5.39, easeOutQuint
    animation = windows, 1, 4.79, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
    animation = windowsOut, 1, 1.49, linear, popin 87%
    animation = fadeIn, 1, 1.73, almostLinear
    animation = fadeOut, 1, 1.46, almostLinear
    animation = fade, 1, 3.03, quick
    animation = layers, 1, 3.81, easeOutQuint
    animation = layersIn, 1, 4, easeOutQuint, fade
    animation = layersOut, 1, 1.5, linear, fade
    animation = fadeLayersIn, 1, 1.79, almostLinear
    animation = fadeLayersOut, 1, 1.39, almostLinear
    animation = workspaces, 1, 1.94, almostLinear, fade
    animation = workspacesIn, 1, 1.21, almostLinear, fade
    animation = workspacesOut, 1, 1.94, almostLinear, fade
}


# Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# godot
#windowrule = workspace 3,class:worn-down
#windowrule = maximize,class:worn-down

#zen picture in picture
# windowrulev2 = float, class:^(zen)$, title:^(Picture-in-Picture)$
hl.window_rule({ match= {class="zen", title="Picture-in-Picture"}, float})

# file roller popup
#windowrule = tile, title:Extract

# VirtualBox settings window
#windowrule = float,initialClass:VirtualBox

exec-once=bash ~/.config/hypr/scripts/startup.sh
